"""Deterministic renderers: structured sections/blocks -> Markdown, semantic
HTML, and WordPress (Gutenberg) block markup.

All three outputs are derived from the same `WriterSection`/`Block` structures
so the prose is generated by the LLM exactly once. No markdown/HTML parser
dependency — we control the block shapes end to end.
"""

from __future__ import annotations

from html import escape

from models.service_writer import Block, WriterSection

_LEVEL = {"H1": 1, "H2": 2, "H3": 3}


def count_words(sections: list[WriterSection]) -> int:
    total = 0
    for s in sections:
        total += len(s.heading.split())
        for b in s.blocks:
            total += len(b.text.split())
            for item in b.items:
                total += len(item.split())
    return total


# ----------------------------------------------------------------------
# Markdown
# ----------------------------------------------------------------------

def _md_block(b: Block) -> str:
    if b.type == "list":
        return "\n".join(f"- {item}" for item in b.items if item)
    if b.type == "subheading":
        return f"{'#' * max(2, min(b.level, 6))} {b.text}"
    if b.type == "cta":
        return f"[{b.text}]({b.href})" if b.href else f"**{b.text}**"
    return b.text  # paragraph


def render_markdown(sections: list[WriterSection]) -> str:
    parts: list[str] = []
    for s in sections:
        level = _LEVEL.get(s.level, 2)
        if s.heading:
            parts.append(f"{'#' * level} {s.heading}")
        for b in s.blocks:
            rendered = _md_block(b)
            if rendered.strip():
                parts.append(rendered)
    return "\n\n".join(parts).strip()


# ----------------------------------------------------------------------
# Semantic HTML
# ----------------------------------------------------------------------

def _html_block(b: Block) -> str:
    if b.type == "list":
        items = "".join(f"<li>{escape(i)}</li>" for i in b.items if i)
        return f"<ul>{items}</ul>"
    if b.type == "subheading":
        lvl = max(2, min(b.level, 6))
        return f"<h{lvl}>{escape(b.text)}</h{lvl}>"
    if b.type == "cta":
        if b.href:
            return f'<p class="cta"><a href="{escape(b.href, quote=True)}">{escape(b.text)}</a></p>'
        return f'<p class="cta"><strong>{escape(b.text)}</strong></p>'
    return f"<p>{escape(b.text)}</p>"


def render_html(sections: list[WriterSection]) -> str:
    parts: list[str] = []
    for s in sections:
        lvl = _LEVEL.get(s.level, 2)
        if s.heading:
            parts.append(f"<h{lvl}>{escape(s.heading)}</h{lvl}>")
        for b in s.blocks:
            parts.append(_html_block(b))
    return "\n".join(parts).strip()


# ----------------------------------------------------------------------
# WordPress (Gutenberg block markup) — paste-ready into the WP block editor
# ----------------------------------------------------------------------

def _wp_heading(text: str, level: int) -> str:
    lvl = max(2, min(level, 6))
    attrs = "" if lvl == 2 else f' {{"level":{lvl}}}'
    return f"<!-- wp:heading{attrs} -->\n<h{lvl}>{escape(text)}</h{lvl}>\n<!-- /wp:heading -->"


def _wp_block(b: Block) -> str:
    if b.type == "list":
        items = "".join(
            f"<!-- wp:list-item -->\n<li>{escape(i)}</li>\n<!-- /wp:list-item -->\n"
            for i in b.items if i
        )
        return f'<!-- wp:list -->\n<ul class="wp-block-list">\n{items}</ul>\n<!-- /wp:list -->'
    if b.type == "subheading":
        return _wp_heading(b.text, b.level)
    if b.type == "cta":
        link = (
            f'<a class="wp-block-button__link wp-element-button" '
            f'href="{escape(b.href, quote=True)}">{escape(b.text)}</a>'
            if b.href
            else f'<a class="wp-block-button__link wp-element-button">{escape(b.text)}</a>'
        )
        return (
            "<!-- wp:buttons -->\n"
            '<div class="wp-block-buttons">\n'
            "<!-- wp:button -->\n"
            f'<div class="wp-block-button">{link}</div>\n'
            "<!-- /wp:button -->\n"
            "</div>\n"
            "<!-- /wp:buttons -->"
        )
    return f"<!-- wp:paragraph -->\n<p>{escape(b.text)}</p>\n<!-- /wp:paragraph -->"


def render_wordpress(sections: list[WriterSection]) -> str:
    parts: list[str] = []
    for s in sections:
        if s.heading:
            parts.append(_wp_heading(s.heading, _LEVEL.get(s.level, 2)))
        for b in s.blocks:
            parts.append(_wp_block(b))
    return "\n\n".join(parts).strip()
