"""Blog article scoring + reoptimization (platform-api).

Blog posts run through `runs`/`module_outputs` and are generated by the
pipeline-api 5-module blog pipeline (brief → sie → research → writer →
sources_cited). Scoring REUSES the nlp-api blog/AEO scorer (`/score-blog-page`,
national scope); reoptimization REGENERATES via the blog `writer` in reoptimize
mode (fed the scorer's deficiencies) and then re-runs `sources_cited` on the new
writer attempt — the blog-specific wrinkle vs. service pages, where the writer
output is directly publishable. Only platform-api can reach nlp-api, so this
orchestration lives here (mirrors `service_page_score`).

Publish reads the `sources_cited` enriched article, so a reoptimize pass must
produce a fresh `sources_cited` attempt — not just a new `writer` attempt — for
the improved article to actually ship.

Persistence: a score is a `blog_score` `module_outputs` row (a scrape/paste of an
external page is a `blog_source_score` row); a reoptimized article is a new
`writer` + `sources_cited` attempt pair. No new table.
"""

from __future__ import annotations

import logging
from typing import Optional

import httpx
from fastapi import HTTPException

from config import settings
from db.supabase_client import get_supabase
from services.local_seo_service import _post_nlp  # reuse the nlp transport
from services.markdown_html import markdown_to_html

logger = logging.getLogger(__name__)

_PIPELINE_TIMEOUT = 600
_WRITE_PATH = "/write"
_SOURCES_CITED_PATH = "/sources-cited"


def _sb():
    return get_supabase()


def _get_run(run_id: str) -> dict:
    run = (_sb().table("runs").select("*").eq("id", run_id).single().execute()).data or {}
    if not run:
        raise HTTPException(status_code=404, detail="run_not_found")
    if run.get("content_type") in ("service_page", "location_page"):
        raise HTTPException(status_code=400, detail="not_a_blog_run")
    return run


def _get_client(client_id: str) -> dict:
    return (_sb().table("clients").select("*").eq("id", client_id).single().execute()).data or {}


def _get_snapshot(run_id: str) -> dict:
    rows = (
        _sb().table("client_context_snapshots").select("*").eq("run_id", run_id).limit(1).execute()
    ).data or []
    return rows[0] if rows else {}


def _latest_output(run_id: str, module: str) -> Optional[dict]:
    """Highest-attempt complete module_output for (run, module), or None."""
    rows = (
        _sb().table("module_outputs")
        .select("id, output_payload, attempt_number")
        .eq("run_id", run_id).eq("module", module).eq("status", "complete")
        .order("attempt_number", desc=True).limit(1).execute()
    ).data or []
    return rows[0] if rows else None


def _next_attempt(run_id: str, module: str) -> int:
    rows = (
        _sb().table("module_outputs").select("attempt_number")
        .eq("run_id", run_id).eq("module", module)
        .order("attempt_number", desc=True).limit(1).execute()
    ).data or []
    return (rows[0]["attempt_number"] + 1) if rows else 1


def _insert_output(run_id: str, module: str, output_payload: dict, cost_usd: Optional[float]) -> str:
    row = {
        "run_id": run_id,
        "module": module,
        "status": "complete",
        "output_payload": output_payload,
        "attempt_number": _next_attempt(run_id, module),
        "cost_usd": cost_usd,
        "completed_at": "now()",
    }
    res = _sb().table("module_outputs").insert(row).execute()
    return (res.data or [{}])[0].get("id", "")


def _sections_to_markdown(article: list) -> str:
    """Reconstruct markdown from the sources_cited enriched_article sections.
    Mirrors routers.publish._sections_to_markdown (kept local so a service never
    imports a router). Figure sections emit their raw HTML verbatim."""
    if not isinstance(article, list):
        return ""
    sections = sorted(
        [s for s in article if isinstance(s, dict)],
        key=lambda s: s.get("order", 0),
    )
    parts = []
    for s in sections:
        if s.get("type") == "figure":
            html = (s.get("html") or "").strip()
            if html:
                parts.append(html)
            continue
        heading = s.get("heading") or ""
        body = s.get("body") or ""
        parts.append(f"## {heading}\n\n{body}" if heading else body)
    return "\n\n".join(parts)


def _blog_title_h1(run_id: str) -> tuple[str, str]:
    """SEO title + on-page H1 from the Brief Generator output (v2.0 Step 3.5),
    so the title/H1 scoring signals fire. Falls back to the run keyword."""
    brief = _latest_output(run_id, "brief")
    p = (brief or {}).get("output_payload") or {}
    title = (p.get("title") or "").strip()
    h1 = (p.get("h1") or "").strip()
    return title, h1


def build_scoring_html(article: list, title: str, h1: str) -> str:
    """Wrap the reconstructed article body with <title> + <h1> so the title/H1
    engines see them (blog sections start at H2)."""
    body_md = _sections_to_markdown(article)
    body_html = markdown_to_html(body_md) if body_md.strip() else ""
    heading = h1 or title or "Article"
    return (
        f"<!doctype html><html><head><title>{title or heading}</title></head>"
        f"<body><h1>{heading}</h1>\n{body_html}</body></html>"
    )


def _business_fields(client: dict) -> tuple[str, str]:
    """(business_name, brand_context) for the blog scorer. brand_context feeds
    entity/ICP framing; national scope means no address/geo is needed."""
    gbp = client.get("gbp") if isinstance(client.get("gbp"), dict) else {}
    business_name = (gbp or {}).get("business_name") or client.get("name") or "Business"
    brand_context = (gbp or {}).get("gbp_category") or client.get("business_location") or ""
    return business_name, brand_context


async def _score_html(run: dict, page_html: str, user_id: Optional[str]) -> dict:
    """Score a blog article's HTML via the nlp-api blog/AEO scorer (national)."""
    client = _get_client(run["client_id"])
    business_name, brand_context = _business_fields(client)
    payload = {
        "keyword": run.get("keyword") or "",
        "page_content": page_html,
        "business_name": business_name,
        "brand_context": brand_context,
        "geo_mode": "national",
    }
    from services import voice_card_service

    payload["voice_card"] = await voice_card_service.get_voice_card(client, user_id=user_id)
    return await _post_nlp("/score-blog-page", payload, user_id=user_id)


async def score_run(run_id: str, user_id: Optional[str] = None) -> dict:
    """Score the run's latest blog article (reconstructed from the sources_cited
    enriched article), persist a `blog_score` module_output, and return the
    ScoreResult (composite + per-engine + deficiencies)."""
    run = _get_run(run_id)
    sc = _latest_output(run_id, "sources_cited")
    if not sc:
        raise HTTPException(status_code=422, detail="article_not_available")
    article = ((sc.get("output_payload") or {}).get("enriched_article") or {}).get("article") or []
    title, h1 = _blog_title_h1(run_id)
    html = build_scoring_html(article, title, h1)
    result = await _score_html(run, html, user_id)
    cost = (result.get("token_usage") or {}).get("cost_usd")
    _insert_output(run_id, "blog_score", result, cost)
    logger.info(
        "blog_page.scored",
        extra={"run_id": run_id, "composite": result.get("composite_score")},
    )
    return result


async def score_external_page(
    run_id: str,
    *,
    source_url: Optional[str] = None,
    source_html: Optional[str] = None,
    user_id: Optional[str] = None,
) -> dict:
    """Score an EXTERNAL article — either scraped from a live URL or pasted by the
    user (WYSIWYG) — via the blog/AEO scorer, persisting a `blog_source_score`
    module_output. Returns the ScoreResult; its `deficiencies` drive the writer's
    first pass on a reoptimize-existing run. Raises on empty content; the
    orchestrator calls it best-effort."""
    run = _get_run(run_id)
    html = (source_html or "").strip()
    if not html and source_url:
        from services.website_scraper import scrapeowl_fetch

        html = (await scrapeowl_fetch(source_url) or "").strip()
    if not html:
        raise HTTPException(status_code=422, detail="source_page_empty")
    result = await _score_html(run, html, user_id)
    cost = (result.get("token_usage") or {}).get("cost_usd")
    _insert_output(run_id, "blog_source_score", result, cost)
    logger.info(
        "blog_page.source_scored",
        extra={"run_id": run_id, "composite": result.get("composite_score")},
    )
    return result


def _cost_of(result: dict) -> Optional[float]:
    """Pipeline cost the same way the orchestrator reads it (top-level cost_usd,
    else metadata.cost_usd)."""
    return result.get("cost_usd") or (result.get("metadata") or {}).get("cost_usd")


async def _post_pipeline(path: str, payload: dict) -> dict:
    url = f"{settings.pipeline_api_url}{path}"
    async with httpx.AsyncClient(timeout=_PIPELINE_TIMEOUT) as client:
        r = await client.post(url, json=payload)
        if r.status_code != 200:
            logger.warning(
                "blog_page.pipeline_http_error",
                extra={"path": path, "status": r.status_code, "body": r.text[:500]},
            )
            raise HTTPException(status_code=502, detail="blog_writer_error")
        return r.json()


async def reoptimize_run(
    run_id: str, deficiencies: list[dict], user_id: Optional[str] = None
) -> dict:
    """Regenerate the article via the blog `writer` in reoptimize mode (fed the
    deficiencies, reusing the run's cached brief/sie/research), persist it as a new
    `writer` attempt, THEN re-run `sources_cited` on that attempt so the improved
    article is what publish reads, then re-score. Returns {page, score}."""
    # Local import to avoid a module-load cycle (orchestrator imports this module
    # inside its functions too).
    from services.orchestrator import _build_sources_cited_payload, _build_writer_payload

    run = _get_run(run_id)
    brief = _latest_output(run_id, "brief")
    sie = _latest_output(run_id, "sie")
    research = _latest_output(run_id, "research")
    writer = _latest_output(run_id, "writer")
    if not (brief and sie and writer):
        raise HTTPException(status_code=422, detail="article_not_available")
    snapshot = _get_snapshot(run_id)
    brief_p = brief.get("output_payload") or {}
    sie_p = sie.get("output_payload") or {}
    research_p = (research or {}).get("output_payload") or {}
    prior_article = (writer.get("output_payload") or {}).get("article") or []

    # Base writer payload (client context + reference-structure mirroring) reused
    # from the orchestrator, then switched into reoptimize mode.
    writer_payload = _build_writer_payload(run, brief_p, sie_p, research_p, snapshot)
    writer_payload["attempt"] = _next_attempt(run_id, "writer")
    writer_payload["mode"] = "reoptimize"
    writer_payload["prior_sections"] = prior_article
    writer_payload["deficiencies"] = deficiencies or []

    new_writer = await _post_pipeline(_WRITE_PATH, writer_payload)
    _insert_output(run_id, "writer", new_writer, _cost_of(new_writer))

    # Re-run sources_cited on the fresh writer attempt (publish reads this).
    sc_payload = _build_sources_cited_payload(run, new_writer, research_p)
    sc_payload["attempt"] = _next_attempt(run_id, "sources_cited")
    new_sc = await _post_pipeline(_SOURCES_CITED_PATH, sc_payload)
    _insert_output(run_id, "sources_cited", new_sc, _cost_of(new_sc))

    score = await score_run(run_id, user_id=user_id)
    logger.info(
        "blog_page.reoptimized",
        extra={"run_id": run_id, "new_composite": score.get("composite_score")},
    )
    return {"page": new_sc, "score": score}


# ── background jobs (deploy-proof score / reoptimize) ─────────────────────────
# Same rationale as service_page_score: the SSE endpoints run the work in-request,
# so a deploy could lose it. As async_jobs the work is durable and the UI
# reconnects (useResumableJob). Results land in module_outputs; the job row stays
# thin and the poller reads the authoritative module_outputs rows.

def _enqueue_job(job_type: str, run_id: str, payload: dict) -> str:
    res = (
        _sb().table("async_jobs")
        .insert({"job_type": job_type, "entity_id": run_id, "payload": payload})
        .execute()
    )
    return res.data[0]["id"]


async def enqueue_score(run_id: str, user_id: Optional[str]) -> str:
    run = _get_run(run_id)
    if not _latest_output(run_id, "sources_cited"):
        raise HTTPException(status_code=422, detail="article_not_available")
    return _enqueue_job("blog_score", run["id"], {"run_id": run_id, "user_id": user_id})


async def enqueue_reoptimize(
    run_id: str, deficiencies: list[dict], user_id: Optional[str]
) -> str:
    run = _get_run(run_id)
    if not _latest_output(run_id, "brief") or not _latest_output(run_id, "writer"):
        raise HTTPException(status_code=422, detail="article_not_available")
    return _enqueue_job(
        "blog_reoptimize", run["id"],
        {"run_id": run_id, "deficiencies": deficiencies or [], "user_id": user_id},
    )


async def _finish_job(job_id: str, work) -> None:
    sb = _sb()
    try:
        summary = await work()
        sb.table("async_jobs").update(
            {"status": "complete", "result": summary, "completed_at": "now()"}
        ).eq("id", job_id).execute()
    except Exception as exc:  # noqa: BLE001 — record the failure for the poller
        detail = getattr(exc, "detail", None) or str(exc)
        logger.warning("blog_page.job_failed", extra={"job_id": job_id, "error": str(detail)})
        sb.table("async_jobs").update(
            {"status": "failed", "error": str(detail)[:500], "completed_at": "now()"}
        ).eq("id", job_id).execute()


async def run_score_job(job: dict) -> None:
    """async_jobs handler for job_type='blog_score'."""
    payload = job.get("payload") or {}

    async def work() -> dict:
        result = await score_run(payload["run_id"], user_id=payload.get("user_id"))
        return {"composite_score": result.get("composite_score")}

    await _finish_job(job["id"], work)


async def run_reoptimize_job(job: dict) -> None:
    """async_jobs handler for job_type='blog_reoptimize'."""
    payload = job.get("payload") or {}

    async def work() -> dict:
        result = await reoptimize_run(
            payload["run_id"], payload.get("deficiencies") or [],
            user_id=payload.get("user_id"),
        )
        return {"composite_score": (result.get("score") or {}).get("composite_score")}

    await _finish_job(job["id"], work)


def get_score_job(job_id: str, run_id: str) -> dict:
    """Poll a blog score/reoptimize job (scoped to the run). On completion the
    score (and, for a reoptimize, the new article) come from module_outputs."""
    rows = (
        _sb().table("async_jobs")
        .select("job_type, status, error, entity_id")
        .eq("id", job_id).limit(1).execute()
    ).data or []
    if not rows or rows[0].get("entity_id") != run_id:
        raise HTTPException(status_code=404, detail="score_job_not_found")
    row = rows[0]
    out: dict = {"status": row["status"], "error": row.get("error")}
    if row["status"] == "complete":
        score = _latest_output(run_id, "blog_score")
        out["score"] = (score or {}).get("output_payload")
        if row["job_type"] == "blog_reoptimize":
            page = _latest_output(run_id, "sources_cited")
            out["page"] = (page or {}).get("output_payload")
    return out
