"""Service Page scoring + reoptimization (platform-api).

Service pages run through `runs`/`module_outputs` and are generated by
pipeline-api's `service_writer`. Scoring REUSES the nlp-api 8-engine scorer in
location-agnostic (`geo_mode='national'`) mode; reoptimization regenerates via
`service_writer` (reoptimize mode, fed the scorer's deficiencies) so the page
keeps its native Markdown/HTML/WordPress renderings + JSON-LD. Only platform-api
can reach nlp-api, so this orchestration lives here (mirrors local_seo_service).

Persistence: a score is a `service_score` `module_outputs` row; a reoptimized
page is a new `service_writer` attempt. No new table.
"""

from __future__ import annotations

import logging
from typing import Optional

import httpx
from fastapi import HTTPException

from config import settings
from db.supabase_client import get_supabase
from services.local_seo_service import _post_nlp  # reuse the nlp transport

logger = logging.getLogger(__name__)

_PIPELINE_TIMEOUT = 600
_SERVICE_WRITE_PATH = "/service-write"


def _sb():
    return get_supabase()


def _get_run(run_id: str) -> dict:
    run = (_sb().table("runs").select("*").eq("id", run_id).single().execute()).data or {}
    if not run:
        raise HTTPException(status_code=404, detail="run_not_found")
    if run.get("content_type") not in ("service_page", "location_page"):
        raise HTTPException(status_code=400, detail="not_a_service_page_run")
    return run


def _get_client(client_id: str) -> dict:
    return (_sb().table("clients").select("*").eq("id", client_id).single().execute()).data or {}


def _get_snapshot(run_id: str) -> dict:
    rows = (
        _sb().table("client_context_snapshots").select("*").eq("run_id", run_id).limit(1).execute()
    ).data or []
    return rows[0] if rows else {}


def _latest_output(run_id: str, module: str) -> Optional[dict]:
    """Highest-attempt complete module_output for (run, module), or None."""
    rows = (
        _sb().table("module_outputs")
        .select("id, output_payload, attempt_number")
        .eq("run_id", run_id).eq("module", module).eq("status", "complete")
        .order("attempt_number", desc=True).limit(1).execute()
    ).data or []
    return rows[0] if rows else None


def _next_attempt(run_id: str, module: str) -> int:
    rows = (
        _sb().table("module_outputs").select("attempt_number")
        .eq("run_id", run_id).eq("module", module)
        .order("attempt_number", desc=True).limit(1).execute()
    ).data or []
    return (rows[0]["attempt_number"] + 1) if rows else 1


def _insert_output(run_id: str, module: str, output_payload: dict, cost_usd: Optional[float]) -> str:
    row = {
        "run_id": run_id,
        "module": module,
        "status": "complete",
        "output_payload": output_payload,
        "attempt_number": _next_attempt(run_id, module),
        "cost_usd": cost_usd,
        "completed_at": "now()",
    }
    res = _sb().table("module_outputs").insert(row).execute()
    return (res.data or [{}])[0].get("id", "")


def build_scoring_html(sw_output: dict) -> str:
    """Wrap the writer's HTML rendering with <title> + <h1> so the title/H1
    scoring engines see them (service_writer sections start at H2)."""
    title = str(sw_output.get("title") or sw_output.get("primary_query") or "").strip()
    h1 = title or str(sw_output.get("primary_query") or "Service")
    body = str((sw_output.get("renderings") or {}).get("html") or "").strip()
    return f"<!doctype html><html><head><title>{title}</title></head><body><h1>{h1}</h1>\n{body}</body></html>"


def _business_fields(client: dict) -> tuple[str, str, str]:
    gbp = client.get("gbp") if isinstance(client.get("gbp"), dict) else {}
    business_name = (gbp or {}).get("business_name") or client.get("name") or "Business"
    gbp_category = (gbp or {}).get("gbp_category") or ""
    address = (gbp or {}).get("address") or client.get("business_location") or ""
    return business_name, gbp_category, address


async def score_run(run_id: str, user_id: Optional[str] = None) -> dict:
    """Score the run's latest service_writer page, persist a `service_score`
    module_output, and return the ScoreResult.

    A `service_page` run scores in location-agnostic `national` mode (geo engines
    don't apply). A `location_page` run is location-targeted, so it scores in
    `local` mode — the geo engines count and the page's location + the client's
    business address are passed through.
    """
    run = _get_run(run_id)
    sw = _latest_output(run_id, "service_writer")
    if not sw:
        raise HTTPException(status_code=422, detail="page_not_available")
    sw_out = sw.get("output_payload") or {}
    client = _get_client(run["client_id"])
    business_name, gbp_category, address = _business_fields(client)
    payload = {
        "keyword": run.get("keyword") or sw_out.get("primary_query") or "",
        "page_content": build_scoring_html(sw_out),
        "business_name": business_name,
        "gbp_category": gbp_category,
    }
    if run.get("content_type") == "location_page":
        payload["geo_mode"] = "local"
        payload["location"] = run.get("location") or ""
        payload["location_code"] = run.get("location_code")
        payload["address"] = address
    else:
        payload["geo_mode"] = "national"
    # The client's distilled brand guide: adds the brand_voice_fit engine and
    # repoints icp_alignment at the real ICP instead of a keyword-derived guess.
    from services import voice_card_service

    payload["voice_card"] = await voice_card_service.get_voice_card(client, user_id=user_id)
    result = await _post_nlp("/score-page", payload, user_id=user_id)
    cost = (result.get("token_usage") or {}).get("cost_usd")
    _insert_output(run_id, "service_score", result, cost)
    logger.info(
        "service_page.scored",
        extra={"run_id": run_id, "composite": result.get("composite_score")},
    )
    return result


async def score_external_page(
    run_id: str, source_url: str, user_id: Optional[str] = None
) -> dict:
    """Scrape a page already published on the client's live site and score it via
    the nlp-api 8-engine scorer, persisting a `source_page_score` module_output.
    Returns the ScoreResult (its `deficiencies` drive the reoptimize generation).

    Mirrors `score_run`'s geo handling (national for service pages, local for
    location pages) but scores the *scraped live HTML* rather than a generated page.
    Raises on scrape/score failure; the orchestrator calls it best-effort."""
    from services.website_scraper import scrapeowl_fetch

    run = _get_run(run_id)
    client = _get_client(run["client_id"])
    business_name, gbp_category, address = _business_fields(client)
    html = await scrapeowl_fetch(source_url)
    if not (html or "").strip():
        raise HTTPException(status_code=422, detail="source_page_empty")
    payload = {
        "keyword": run.get("keyword") or "",
        "page_content": html,
        "business_name": business_name,
        "gbp_category": gbp_category,
    }
    if run.get("content_type") == "location_page":
        payload["geo_mode"] = "local"
        payload["location"] = run.get("location") or ""
        payload["location_code"] = run.get("location_code")
        payload["address"] = address
    else:
        payload["geo_mode"] = "national"
    # The client's distilled brand guide: adds the brand_voice_fit engine and
    # repoints icp_alignment at the real ICP instead of a keyword-derived guess.
    from services import voice_card_service

    payload["voice_card"] = await voice_card_service.get_voice_card(client, user_id=user_id)
    result = await _post_nlp("/score-page", payload, user_id=user_id)
    cost = (result.get("token_usage") or {}).get("cost_usd")
    _insert_output(run_id, "source_page_score", result, cost)
    logger.info(
        "service_page.source_scored",
        extra={"run_id": run_id, "url": source_url, "composite": result.get("composite_score")},
    )
    return result


def structural_deficiency(run: dict, snapshot: dict) -> Optional[dict]:
    """A synthetic scorer-deficiency describing structural drift of the run's latest
    service_writer page vs the client's reference structure, or None when the gate
    is off / there's no reference / the layout already matches.

    Folded into the single auto-reoptimize pass (see orchestrator Stage C) so the
    writer fixes the drift through its existing deficiency channel — no extra
    reopt, no pipeline-api change. Reads the reference from the frozen snapshot
    (`page_structures['service'|'location']`). Best-effort: returns None on any
    failure so it never blocks the run."""
    if not settings.service_page_structure_gate_enabled:
        return None
    from services.page_structure_eval import (
        extract_outline_from_html,
        structure_deficiency as _deficiency,
    )
    from services.page_structure_render import usable_analysis

    structures = snapshot.get("page_structures") or {}
    key = "location" if run.get("content_type") == "location_page" else "service"
    reference = usable_analysis(structures.get(key))
    if not reference:
        return None
    sw = _latest_output(run["id"], "service_writer")
    if not sw:
        return None
    try:
        generated = extract_outline_from_html(build_scoring_html(sw.get("output_payload") or {}))
    except Exception:  # noqa: BLE001 — structural scoring must never block the run
        logger.warning("service_page.structure_extract_failed", extra={"run_id": run.get("id")})
        return None
    return _deficiency(
        reference, generated, label=key, min_composite=settings.service_page_structure_min_composite
    )


async def _post_pipeline(path: str, payload: dict) -> dict:
    url = f"{settings.pipeline_api_url}{path}"
    async with httpx.AsyncClient(timeout=_PIPELINE_TIMEOUT) as client:
        r = await client.post(url, json=payload)
        if r.status_code != 200:
            logger.warning(
                "service_page.pipeline_http_error",
                extra={"path": path, "status": r.status_code, "body": r.text[:500]},
            )
            raise HTTPException(status_code=502, detail="service_writer_error")
        return r.json()


def _client_context(snapshot: dict) -> dict:
    return {
        "brand_guide_text": snapshot.get("brand_guide_text") or "",
        "icp_text": snapshot.get("icp_text") or "",
        "website_analysis": snapshot.get("website_analysis"),
        "website_analysis_unavailable": snapshot.get("website_analysis_unavailable", False),
    }


async def reoptimize_run(
    run_id: str, deficiencies: list[dict], user_id: Optional[str] = None
) -> dict:
    """Regenerate the page via service_writer (reoptimize mode, fed the
    deficiencies), persist it as a new service_writer attempt, then re-score.
    Returns {page, score}."""
    run = _get_run(run_id)
    sb_out = _latest_output(run_id, "service_brief")
    sw_out = _latest_output(run_id, "service_writer")
    if not sb_out or not sw_out:
        raise HTTPException(status_code=422, detail="page_not_available")
    snapshot = _get_snapshot(run_id)
    services = run.get("services") or []
    payload = {
        "run_id": run_id,
        "attempt": _next_attempt(run_id, "service_writer"),
        "service_brief_output": sb_out.get("output_payload") or {},
        "client_context": _client_context(snapshot),
        "mode": "reoptimize",
        "prior_sections": (sw_out.get("output_payload") or {}).get("sections") or [],
        "deficiencies": deficiencies or [],
        # Preserve the page's location framing across the reoptimize pass.
        "page_type": "location" if run.get("content_type") == "location_page" else "service",
        "location": run.get("location"),
        "services": [str(s).strip() for s in services if isinstance(services, list) and str(s).strip()],
    }
    page = await _post_pipeline(_SERVICE_WRITE_PATH, payload)
    cost = (page.get("metadata") or {}).get("cost_usd")
    _insert_output(run_id, "service_writer", page, cost)
    score = await score_run(run_id, user_id=user_id)
    logger.info(
        "service_page.reoptimized",
        extra={"run_id": run_id, "new_composite": score.get("composite_score")},
    )
    return {"page": page, "score": score}


# ── background jobs (deploy-proof score / reoptimize) ─────────────────────────
# The SSE endpoints above run the work inside the HTTP request, so a deploy
# killed it with no server-side record of the intent — the user was told to run
# it again. As async_jobs the work is durable: a deploy's shutdown requeues the
# row, the new container finishes it, and the UI reconnects (useResumableJob)
# instead of prompting. Results still land in module_outputs exactly as before;
# the job row's `result` stays thin and the poll endpoint reads the
# authoritative module_outputs rows, so a multi-hundred-KB page payload isn't
# duplicated into async_jobs.

def _enqueue_job(job_type: str, run: dict, payload: dict) -> str:
    res = (
        _sb().table("async_jobs")
        .insert({"job_type": job_type, "entity_id": run["id"], "payload": payload})
        .execute()
    )
    return res.data[0]["id"]


async def enqueue_score(run_id: str, user_id: Optional[str]) -> str:
    """Validate (the run exists and has a page — fail fast with the same 422 the
    SSE path gave), then enqueue a `service_page_score` job."""
    run = _get_run(run_id)
    if not _latest_output(run_id, "service_writer"):
        raise HTTPException(status_code=422, detail="page_not_available")
    return _enqueue_job(
        "service_page_score", run, {"run_id": run_id, "user_id": user_id}
    )


async def enqueue_reoptimize(
    run_id: str, deficiencies: list[dict], user_id: Optional[str]
) -> str:
    """Validate, then enqueue a `service_page_reoptimize` job carrying the
    deficiency selection the user made on screen."""
    run = _get_run(run_id)
    if not _latest_output(run_id, "service_brief") or not _latest_output(run_id, "service_writer"):
        raise HTTPException(status_code=422, detail="page_not_available")
    return _enqueue_job(
        "service_page_reoptimize", run,
        {"run_id": run_id, "deficiencies": deficiencies or [], "user_id": user_id},
    )


async def _finish_job(job_id: str, work) -> None:
    """Run one job's work coroutine and record the terminal state for the
    poller. A requeued duplicate (deploy mid-run) simply re-runs the work and
    persists a fresh module_outputs attempt — reads use the latest, so state
    converges (same idempotency class as the local_seo generate jobs)."""
    sb = _sb()
    try:
        summary = await work()
        sb.table("async_jobs").update(
            {"status": "complete", "result": summary, "completed_at": "now()"}
        ).eq("id", job_id).execute()
    except Exception as exc:  # noqa: BLE001 — record the failure for the poller
        detail = getattr(exc, "detail", None) or str(exc)
        logger.warning(
            "service_page.job_failed", extra={"job_id": job_id, "error": str(detail)}
        )
        sb.table("async_jobs").update(
            {"status": "failed", "error": str(detail)[:500], "completed_at": "now()"}
        ).eq("id", job_id).execute()


async def run_score_job(job: dict) -> None:
    """async_jobs handler for job_type='service_page_score'."""
    payload = job.get("payload") or {}

    async def work() -> dict:
        result = await score_run(payload["run_id"], user_id=payload.get("user_id"))
        return {"composite_score": result.get("composite_score")}

    await _finish_job(job["id"], work)


async def run_reoptimize_job(job: dict) -> None:
    """async_jobs handler for job_type='service_page_reoptimize'."""
    payload = job.get("payload") or {}

    async def work() -> dict:
        result = await reoptimize_run(
            payload["run_id"], payload.get("deficiencies") or [],
            user_id=payload.get("user_id"),
        )
        return {"composite_score": (result.get("score") or {}).get("composite_score")}

    await _finish_job(job["id"], work)


def get_score_job(job_id: str, run_id: str) -> dict:
    """Poll a score/reoptimize job (scoped to the run). On completion the score
    (and, for a reoptimize, the new page) come from module_outputs — the
    authoritative store the job wrote — not from the job row."""
    rows = (
        _sb().table("async_jobs")
        .select("job_type, status, error, entity_id")
        .eq("id", job_id).limit(1).execute()
    ).data or []
    if not rows or rows[0].get("entity_id") != run_id:
        raise HTTPException(status_code=404, detail="score_job_not_found")
    row = rows[0]
    out: dict = {"status": row["status"], "error": row.get("error")}
    if row["status"] == "complete":
        score = _latest_output(run_id, "service_score")
        out["score"] = (score or {}).get("output_payload")
        if row["job_type"] == "service_page_reoptimize":
            page = _latest_output(run_id, "service_writer")
            out["page"] = (page or {}).get("output_payload")
    return out
