"""Service Page scoring + reoptimization (platform-api).

Service pages run through `runs`/`module_outputs` and are generated by
pipeline-api's `service_writer`. Scoring REUSES the nlp-api 8-engine scorer in
location-agnostic (`geo_mode='national'`) mode; reoptimization regenerates via
`service_writer` (reoptimize mode, fed the scorer's deficiencies) so the page
keeps its native Markdown/HTML/WordPress renderings + JSON-LD. Only platform-api
can reach nlp-api, so this orchestration lives here (mirrors local_seo_service).

Persistence: a score is a `service_score` `module_outputs` row; a reoptimized
page is a new `service_writer` attempt. No new table.
"""

from __future__ import annotations

import logging
from typing import Optional

import httpx
from fastapi import HTTPException

from config import settings
from db.supabase_client import get_supabase
from services.local_seo_service import _post_nlp  # reuse the nlp transport

logger = logging.getLogger(__name__)

_PIPELINE_TIMEOUT = 600
_SERVICE_WRITE_PATH = "/service-write"


def _sb():
    return get_supabase()


def _get_run(run_id: str) -> dict:
    run = (_sb().table("runs").select("*").eq("id", run_id).single().execute()).data or {}
    if not run:
        raise HTTPException(status_code=404, detail="run_not_found")
    if run.get("content_type") != "service_page":
        raise HTTPException(status_code=400, detail="not_a_service_page_run")
    return run


def _get_client(client_id: str) -> dict:
    return (_sb().table("clients").select("*").eq("id", client_id).single().execute()).data or {}


def _get_snapshot(run_id: str) -> dict:
    rows = (
        _sb().table("client_context_snapshots").select("*").eq("run_id", run_id).limit(1).execute()
    ).data or []
    return rows[0] if rows else {}


def _latest_output(run_id: str, module: str) -> Optional[dict]:
    """Highest-attempt complete module_output for (run, module), or None."""
    rows = (
        _sb().table("module_outputs")
        .select("id, output_payload, attempt_number")
        .eq("run_id", run_id).eq("module", module).eq("status", "complete")
        .order("attempt_number", desc=True).limit(1).execute()
    ).data or []
    return rows[0] if rows else None


def _next_attempt(run_id: str, module: str) -> int:
    rows = (
        _sb().table("module_outputs").select("attempt_number")
        .eq("run_id", run_id).eq("module", module)
        .order("attempt_number", desc=True).limit(1).execute()
    ).data or []
    return (rows[0]["attempt_number"] + 1) if rows else 1


def _insert_output(run_id: str, module: str, output_payload: dict, cost_usd: Optional[float]) -> str:
    row = {
        "run_id": run_id,
        "module": module,
        "status": "complete",
        "output_payload": output_payload,
        "attempt_number": _next_attempt(run_id, module),
        "cost_usd": cost_usd,
        "completed_at": "now()",
    }
    res = _sb().table("module_outputs").insert(row).execute()
    return (res.data or [{}])[0].get("id", "")


def build_scoring_html(sw_output: dict) -> str:
    """Wrap the writer's HTML rendering with <title> + <h1> so the title/H1
    scoring engines see them (service_writer sections start at H2)."""
    title = str(sw_output.get("title") or sw_output.get("primary_query") or "").strip()
    h1 = title or str(sw_output.get("primary_query") or "Service")
    body = str((sw_output.get("renderings") or {}).get("html") or "").strip()
    return f"<!doctype html><html><head><title>{title}</title></head><body><h1>{h1}</h1>\n{body}</body></html>"


def _business_fields(client: dict) -> tuple[str, str]:
    gbp = client.get("gbp") if isinstance(client.get("gbp"), dict) else {}
    business_name = (gbp or {}).get("business_name") or client.get("name") or "Business"
    gbp_category = (gbp or {}).get("gbp_category") or ""
    return business_name, gbp_category


async def score_run(run_id: str, user_id: Optional[str] = None) -> dict:
    """Score the run's latest service_writer page (national / no-location mode),
    persist a `service_score` module_output, and return the ScoreResult."""
    run = _get_run(run_id)
    sw = _latest_output(run_id, "service_writer")
    if not sw:
        raise HTTPException(status_code=422, detail="page_not_available")
    sw_out = sw.get("output_payload") or {}
    client = _get_client(run["client_id"])
    business_name, gbp_category = _business_fields(client)
    payload = {
        "keyword": run.get("keyword") or sw_out.get("primary_query") or "",
        "geo_mode": "national",
        "page_content": build_scoring_html(sw_out),
        "business_name": business_name,
        "gbp_category": gbp_category,
    }
    result = await _post_nlp("/score-page", payload, user_id=user_id)
    cost = (result.get("token_usage") or {}).get("cost_usd")
    _insert_output(run_id, "service_score", result, cost)
    logger.info(
        "service_page.scored",
        extra={"run_id": run_id, "composite": result.get("composite_score")},
    )
    return result


async def _post_pipeline(path: str, payload: dict) -> dict:
    url = f"{settings.pipeline_api_url}{path}"
    async with httpx.AsyncClient(timeout=_PIPELINE_TIMEOUT) as client:
        r = await client.post(url, json=payload)
        if r.status_code != 200:
            logger.warning(
                "service_page.pipeline_http_error",
                extra={"path": path, "status": r.status_code, "body": r.text[:500]},
            )
            raise HTTPException(status_code=502, detail="service_writer_error")
        return r.json()


def _client_context(snapshot: dict) -> dict:
    return {
        "brand_guide_text": snapshot.get("brand_guide_text") or "",
        "icp_text": snapshot.get("icp_text") or "",
        "website_analysis": snapshot.get("website_analysis"),
        "website_analysis_unavailable": snapshot.get("website_analysis_unavailable", False),
    }


async def reoptimize_run(
    run_id: str, deficiencies: list[dict], user_id: Optional[str] = None
) -> dict:
    """Regenerate the page via service_writer (reoptimize mode, fed the
    deficiencies), persist it as a new service_writer attempt, then re-score.
    Returns {page, score}."""
    run = _get_run(run_id)
    sb_out = _latest_output(run_id, "service_brief")
    sw_out = _latest_output(run_id, "service_writer")
    if not sb_out or not sw_out:
        raise HTTPException(status_code=422, detail="page_not_available")
    snapshot = _get_snapshot(run_id)
    payload = {
        "run_id": run_id,
        "attempt": _next_attempt(run_id, "service_writer"),
        "service_brief_output": sb_out.get("output_payload") or {},
        "client_context": _client_context(snapshot),
        "mode": "reoptimize",
        "prior_sections": (sw_out.get("output_payload") or {}).get("sections") or [],
        "deficiencies": deficiencies or [],
    }
    page = await _post_pipeline(_SERVICE_WRITE_PATH, payload)
    cost = (page.get("metadata") or {}).get("cost_usd")
    _insert_output(run_id, "service_writer", page, cost)
    score = await score_run(run_id, user_id=user_id)
    logger.info(
        "service_page.reoptimized",
        extra={"run_id": run_id, "new_composite": score.get("composite_score")},
    )
    return {"page": page, "score": score}
