"""SerMaStr strategy review → Google Doc.

Renders a completed `strategy_reviews` row as an **internal** strategy document
and publishes it as a Google Doc in the client's Drive folder (the shared
`services/google_docs` path the Maps/Brand reports use).

Deliberately internal-facing: the doc carries the full review — proposal costs,
assignee hints, senior-escalation flags, SOP citations, halt-and-ask questions —
i.e. the agency's own strategic reasoning, not a client deliverable (the spec's
§8 non-goal is "no client-facing output"; the Client Reporting module owns
that). The doc is stamped INTERNAL at the top so it can't be mistaken for a
client report if the folder is shared.

No LLM here — the review is already written; this only formats + publishes. The
markdown renderer is pure (unit-tested); only the publish touches the network.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from db.supabase_client import get_supabase
from services.google_docs import GoogleDocError, create_google_doc, resolve_drive_folder

logger = logging.getLogger(__name__)

_TRIGGER_LABELS = {
    "scheduled": "Weekly review",
    "escalation": "Escalation brief",
    "on_demand": "On-demand review",
}
_REQUIRES_LABELS = {
    "senior": "SENIOR SIGN-OFF (Kyle/Ryan)",
    "approval": "needs approval",
    "none": "no approval needed",
}
_STATUS_LABELS = {
    "approved": "APPROVED",
    "dismissed": "dismissed",
    "proposed": "awaiting decision",
    "expired": "expired",
}


def _esc(value) -> str:
    """Flatten a value for safe inline Markdown (no stray newlines breaking lists)."""
    return str(value).replace("\n", " ").strip()


def render_markdown(client_name: str, review: dict, date_str: str) -> str:
    """Render a completed strategy review as the internal Google Doc body. Pure."""
    trigger = review.get("trigger") or "on_demand"
    proposals = review.get("proposals") or []
    findings = review.get("findings") or []
    questions = review.get("questions") or []

    lines = [
        f"# Strategist Review — {client_name}",
        f"_{_TRIGGER_LABELS.get(trigger, trigger)} · {date_str}_",
        "",
        "> **INTERNAL — agency strategy. Not a client deliverable.** "
        "Contains costs, assignees and escalation calls; do not share with the client.",
        "",
    ]

    assessment = (review.get("assessment") or "").strip()
    if assessment:
        lines += ["## Assessment", assessment, ""]

    # Open questions first — these are the halt-and-ask calls needing a human.
    if questions:
        lines += ["## Needs a human call", ""]
        lines += [f"- {_esc(q)}" for q in questions]
        lines.append("")

    if proposals:
        lines += ["## Proposals", ""]
        for i, p in enumerate(proposals, start=1):
            title = _esc(p.get("title") or f"Proposal {i}")
            status = _STATUS_LABELS.get(p.get("status"), p.get("status") or "")
            requires = _REQUIRES_LABELS.get(p.get("requires"), p.get("requires") or "")
            lines.append(f"### {i}. {title}")
            meta = [f"**{status}**"] if status else []
            if requires:
                meta.append(requires)
            if p.get("assignee_hint"):
                meta.append(f"assignee: {_esc(p['assignee_hint'])}")
            if p.get("effort"):
                meta.append(f"{_esc(p['effort'])} effort")
            if isinstance(p.get("est_cost_usd"), (int, float)):
                meta.append(f"~${round(p['est_cost_usd']):,}")
            if meta:
                lines.append(" · ".join(meta))
            if p.get("action"):
                lines += ["", f"**Action:** {(p['action'] or '').strip()}"]
            if p.get("rationale"):
                lines += ["", f"**Why:** {(p['rationale'] or '').strip()}"]
            if p.get("sop_citation"):
                lines += ["", f"_Per {_esc(p['sop_citation'])}_"]
            lines.append("")

    if findings:
        lines += ["## Findings", ""]
        for f in findings:
            synthesis = (f.get("synthesis") or "").strip()
            if not synthesis:
                continue
            cite = f" _({_esc(f['sop_citation'])})_" if f.get("sop_citation") else ""
            refs = f.get("signal_refs") or []
            ref_str = f"  \n  Signals: {_esc(', '.join(str(r) for r in refs))}" if refs else ""
            lines.append(f"- {synthesis}{cite}{ref_str}")
        lines.append("")

    lines += [
        "---",
        f"_Generated by SerMaStr ({_esc(review.get('model') or 'strategist')}). "
        "Proposes only — nothing is executed until a human approves it._",
    ]
    return "\n".join(lines)


def _doc_title(client_name: str, trigger: str, date_str: str) -> str:
    label = _TRIGGER_LABELS.get(trigger, "Strategist Review")
    return f"Strategist Review — {client_name} — {label} — {date_str}".replace("  ", " ").strip(" —")


async def publish_review(review_id: str) -> dict:
    """Render + publish one completed strategy review as a Google Doc in the
    client's Drive folder, and persist the doc link back on the row. Returns
    {doc_id, doc_url}. Raises GoogleDocError (mapped by the caller) on any
    missing prerequisite or webhook failure."""
    supabase = get_supabase()
    rows = (
        supabase.table("strategy_reviews")
        .select("id, client_id, trigger, status, model, assessment, findings, proposals, questions, created_at")
        .eq("id", review_id).limit(1).execute()
    ).data
    if not rows:
        raise GoogleDocError("review_not_found")
    review = rows[0]
    if review.get("status") != "complete":
        raise GoogleDocError("review_not_complete")

    client_rows = (
        supabase.table("clients")
        .select("name, google_drive_folder_id, drive_folders")
        .eq("id", review["client_id"]).limit(1).execute()
    ).data
    if not client_rows:
        raise GoogleDocError("client_not_found")
    client = client_rows[0]
    folder_id = resolve_drive_folder(client, None)
    if not folder_id:
        raise GoogleDocError("missing_google_drive_folder_id")

    client_name = client.get("name") or "Client"
    date_str = datetime.now(timezone.utc).strftime("%-d %b %Y")
    markdown = render_markdown(client_name, review, date_str)
    title = _doc_title(client_name, review.get("trigger") or "on_demand", date_str)

    doc = await create_google_doc(folder_id, title, markdown)

    published_at = datetime.now(timezone.utc).isoformat()
    try:
        supabase.table("strategy_reviews").update({
            "published_doc_id": doc.get("doc_id"),
            "published_doc_url": doc.get("doc_url"),
            "published_at": published_at,
        }).eq("id", review_id).execute()
    except Exception as exc:  # the doc exists; persistence is best-effort
        logger.warning("strategy_report.persist_failed", extra={"review_id": review_id, "error": str(exc)})

    logger.info("strategy_report.published", extra={"review_id": review_id, "doc_id": doc.get("doc_id")})
    return {"doc_id": doc.get("doc_id"), "doc_url": doc.get("doc_url"), "published_at": published_at}
