"""Step 3.6 — Deterministic brand & ICP placement plan.

Pre-allocates which H2 sections must carry (a) a brand mention and (b)
an ICP callout, before any section LLM runs. The section writer reads
this plan per-H2 and stamps a hard `MUST_MENTION_BRAND` / `MUST_NOT_
MENTION_BRAND` directive plus an `ICP_CALLOUT_HOOK` into the prompt —
replacing the previous soft "across the article, mention 1–2 times…
let another section carry it" guidance.

Why this exists:
  Each H2 section is generated by an independent LLM call. The old
  prompt asked every call to coordinate on a 1–2-times-total mention
  budget without any of them knowing what the others did. In practice
  every call defaulted to "let another carry it" and the article
  shipped with zero brand mentions and no ICP callout. Pre-allocating
  the placement deterministically up front turns coordination into a
  per-call boolean ("you mention; you don't") and guarantees coverage.

Selection logic:
  brand_anchor_order:
    1. If `brand_name` is empty → no anchor.
    2. Score each H2 by token-overlap with `client_services`. Ties go
       to the H2 with the lowest `order` (most prominent in the article).
    3. If no service overlap exists, fall back to the first content H2.

  icp_anchor_order:
    1. If `audience_pain_points` and `audience_verticals` are both
       empty → no anchor.
    2. Score each H2 by token-overlap with pain points and verticals.
    3. If the highest scorer is the brand_anchor_order, prefer the
       second-highest (variety guarantee). Tie-breaks lowest order.
    4. If no audience overlap exists, fall back to the first content
       H2 that is not the brand anchor.
    5. The hook is the specific pain point / vertical phrase that
       matched best, so the section prompt can ground its callout
       concretely instead of generically.

Tokenization:
  - Lowercased, alphanumeric tokens only.
  - Stopwords filtered (a small fixed list, no NLTK dependency).
  - Token-set overlap (intersection size) — NOT Jaccard, because we
    want long descriptive service names ("influencer marketing
    campaigns") to score higher than short ones ("ads") when they
    happen to share more tokens with the H2 heading.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Optional

from models.writer import BrandVoiceCard

logger = logging.getLogger(__name__)


_STOPWORDS = frozenset({
    "a", "an", "and", "are", "as", "at", "be", "but", "by", "for",
    "from", "has", "have", "in", "is", "it", "its", "of", "on", "or",
    "that", "the", "to", "was", "were", "will", "with", "your", "you",
    "this", "these", "those", "how", "why", "what", "when", "where",
    "vs", "via",
})

_TOKEN_RE = re.compile(r"[a-z0-9]+")


@dataclass
class H2PlacementDirective:
    """Per-H2 directives consumed by the section writer."""

    must_mention_brand: bool = False
    must_not_mention_brand: bool = False
    icp_callout_hook: Optional[str] = None


@dataclass
class BrandPlacementPlan:
    """Output of `build_brand_placement_plan`.

    `directives` is keyed by H2 `order`. Sections whose order is not in
    the map should treat both flags as False / None (i.e. fall back to
    the soft default — no forced mention, no forced ICP hook).
    """

    directives: dict[int, H2PlacementDirective] = field(default_factory=dict)
    brand_anchor_order: Optional[int] = None
    icp_anchor_order: Optional[int] = None
    icp_hook_phrase: Optional[str] = None

    def for_order(self, order: int) -> H2PlacementDirective:
        return self.directives.get(order, H2PlacementDirective())


def _tokens(text: str) -> set[str]:
    if not text:
        return set()
    return {
        t for t in _TOKEN_RE.findall(text.lower())
        if t not in _STOPWORDS and len(t) > 1
    }


def _overlap_score(heading_tokens: set[str], phrases: list[str]) -> tuple[int, Optional[str]]:
    """Return (best_overlap, best_phrase). best_phrase is the phrase
    that contributed the best score; None if no overlap."""
    best = 0
    best_phrase: Optional[str] = None
    for phrase in phrases:
        if not phrase:
            continue
        overlap = len(heading_tokens & _tokens(phrase))
        if overlap > best:
            best = overlap
            best_phrase = phrase
    return best, best_phrase


def _content_h2s(heading_structure: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Body-content H2s, sorted by `order`. FAQ/conclusion H2s are
    excluded — those are written by their own pipeline steps."""
    return sorted(
        [
            h for h in heading_structure
            if isinstance(h, dict)
            and h.get("level") == "H2"
            and h.get("type") == "content"
        ],
        key=lambda h: h.get("order", 0),
    )


def _pick_anchor(
    h2s: list[dict[str, Any]],
    phrases: list[str],
    *,
    exclude_order: Optional[int] = None,
) -> tuple[Optional[int], Optional[str]]:
    """Score each candidate H2 against `phrases` (token overlap), pick
    the highest scorer. Tie-break: lowest order. Returns
    (h2_order, matched_phrase)."""
    if not h2s:
        return None, None

    candidates = [h for h in h2s if h.get("order") != exclude_order]
    if not candidates:
        return None, None

    scored: list[tuple[int, int, Optional[str], dict]] = []
    for h2 in candidates:
        toks = _tokens(h2.get("text") or "")
        score, phrase = _overlap_score(toks, phrases) if phrases else (0, None)
        scored.append((score, h2.get("order", 0), phrase, h2))

    # Highest score wins; tie-break lowest order.
    scored.sort(key=lambda t: (-t[0], t[1]))
    top_score, top_order, top_phrase, _ = scored[0]
    if top_score == 0:
        # No phrase overlap — fall back to the first H2 (already sorted
        # by order via _content_h2s, so candidates[0] is the lowest-
        # order non-excluded H2).
        return candidates[0].get("order"), None
    return top_order, top_phrase


def build_brand_placement_plan(
    heading_structure: list[dict[str, Any]],
    brand_voice_card: Optional[BrandVoiceCard],
) -> BrandPlacementPlan:
    """Pick exactly one H2 to anchor the brand mention and one H2 to
    anchor the ICP callout. Returns an empty plan when there's nothing
    to anchor (no brand_name, no audience signals, or no content H2s).
    """
    plan = BrandPlacementPlan()

    h2s = _content_h2s(heading_structure)
    if not h2s:
        return plan
    if brand_voice_card is None:
        return plan

    brand_name = (brand_voice_card.brand_name or "").strip()
    services = [s for s in (brand_voice_card.client_services or []) if s]
    pain_points = [p for p in (brand_voice_card.audience_pain_points or []) if p]
    verticals = [v for v in (brand_voice_card.audience_verticals or []) if v]

    if brand_name:
        anchor_order, _ = _pick_anchor(h2s, services)
        if anchor_order is not None:
            plan.brand_anchor_order = anchor_order

    if pain_points or verticals:
        # Pain points carry more semantic weight for an ICP callout
        # than verticals — a pain point names the unmet need; a vertical
        # is a category. Score against the combined list but prefer
        # pain-point matches as the hook phrase by listing them first
        # (the scorer picks the first phrase with the best overlap).
        icp_anchor_order, hook = _pick_anchor(
            h2s, pain_points + verticals,
            exclude_order=plan.brand_anchor_order,
        )
        if icp_anchor_order is not None:
            plan.icp_anchor_order = icp_anchor_order
            plan.icp_hook_phrase = hook

    # Build the per-order directive map. Every content H2 gets an
    # entry: anchors get `must_mention_brand=True` (or hook=…); all
    # other H2s get `must_not_mention_brand=True` so they can't punt
    # the mention into themselves either.
    for h2 in h2s:
        order = h2.get("order")
        if not isinstance(order, int):
            continue
        directive = H2PlacementDirective()
        if plan.brand_anchor_order is not None:
            if order == plan.brand_anchor_order:
                directive.must_mention_brand = True
            else:
                directive.must_not_mention_brand = True
        if plan.icp_anchor_order == order:
            directive.icp_callout_hook = plan.icp_hook_phrase or (
                # Fallback hook when no phrase matched but we still
                # forced an anchor: pick the first available signal.
                (pain_points or verticals or [None])[0]
            )
        plan.directives[order] = directive

    logger.info(
        "writer.brand_placement.plan",
        extra={
            "brand_anchor_order": plan.brand_anchor_order,
            "icp_anchor_order": plan.icp_anchor_order,
            "icp_hook_phrase": plan.icp_hook_phrase,
            "h2_count": len(h2s),
            "has_brand_name": bool(brand_name),
            "has_audience_signals": bool(pain_points or verticals),
        },
    )

    return plan
