"""Unit tests for services.strategy_report.render_markdown — the pure formatter
that turns a completed strategy review into the internal Google Doc body. No DB /
no network (publish_review's I/O is covered by integration testing)."""

from __future__ import annotations

from datetime import datetime, timezone

from services import strategy_report as sr

NOW = datetime(2026, 7, 4, 12, 0, tzinfo=timezone.utc)


def _review(**over) -> dict:
    r = {
        "trigger": "on_demand",
        "status": "complete",
        "model": "claude-sonnet-4-6",
        "assessment": "Organic is stable but the local pack is slipping in the north.",
        "findings": [
            {"synthesis": "Maps decline + off-topic content = vector confusion.",
             "sop_citation": "How To Rank In Google Maps SOP §Relevance",
             "signal_refs": ["maps:emergency plumber", "content:blog"]},
            {"synthesis": "", "sop_citation": "", "signal_refs": []},  # dropped
        ],
        "proposals": [
            {"title": "Fund a link round", "action": "Add 10 niche edits to the money page",
             "rationale": "RD gap vs page-1 median", "sop_citation": "Link Building SOP §RD",
             "est_cost_usd": 135, "effort": "medium", "assignee_hint": "Kyle",
             "status": "proposed", "requires": "approval"},
            {"title": "Reinstatement", "action": "File a GBP reinstatement",
             "rationale": "Listing suspended", "sop_citation": "",
             "status": "approved", "requires": "senior"},
        ],
        "questions": ["No SOP owns the DBA question — Kyle/Ryan call."],
    }
    r.update(over)
    return r


def test_render_has_internal_banner_and_title():
    md = sr.render_markdown("First Class Roofing", _review(), "5 Jul 2026")
    assert md.startswith("# Strategist Review — First Class Roofing")
    assert "INTERNAL" in md and "Not a client deliverable" in md


def test_render_includes_full_proposal_detail():
    md = sr.render_markdown("Acme", _review(), "5 Jul 2026")
    # Internal fields that must NOT be stripped (this is the internal doc).
    assert "~$135" in md
    assert "assignee: Kyle" in md
    assert "medium effort" in md
    assert "SENIOR SIGN-OFF (Kyle/Ryan)" in md
    assert "APPROVED" in md
    assert "Add 10 niche edits to the money page" in md


def test_render_sections_and_questions():
    md = sr.render_markdown("Acme", _review(), "5 Jul 2026")
    assert "## Assessment" in md
    assert "## Needs a human call" in md
    assert "DBA question" in md
    assert "## Proposals" in md
    assert "## Findings" in md
    assert "vector confusion" in md


def test_render_drops_empty_findings():
    md = sr.render_markdown("Acme", _review(), "5 Jul 2026")
    # Exactly one finding bullet survives (the empty-synthesis one is skipped).
    assert md.count("Signals: ") == 1


def test_render_omits_empty_sections():
    review = _review(findings=[], proposals=[], questions=[], assessment="")
    md = sr.render_markdown("Acme", review, "5 Jul 2026")
    assert "## Proposals" not in md
    assert "## Findings" not in md
    assert "## Needs a human call" not in md
    assert "## Assessment" not in md
    # Still a valid doc: header + banner + footer.
    assert md.startswith("# Strategist Review — Acme")
    assert "Generated by SerMaStr" in md


def test_doc_title_shape():
    assert sr._doc_title("Acme", "escalation", "5 Jul 2026") == (
        "Strategist Review — Acme — Escalation brief — 5 Jul 2026"
    )


# ---------------------------------------------------------------------------
# _review_date — the doc is dated when the review RAN, not when it's exported.
# ---------------------------------------------------------------------------
def test_review_date_uses_created_at_not_export_time():
    review = {"created_at": "2026-07-01T17:57:07.83+00:00"}
    assert sr._review_date(review, NOW).strftime("%-d %b %Y") == "1 Jul 2026"


def test_review_date_handles_z_suffix():
    review = {"created_at": "2026-06-30T09:00:00Z"}
    assert sr._review_date(review, NOW).date().isoformat() == "2026-06-30"


def test_review_date_naive_timestamp_gets_utc():
    d = sr._review_date({"created_at": "2026-06-30T09:00:00"}, NOW)
    assert d.tzinfo is not None


def test_review_date_falls_back_to_now_on_bad_value():
    assert sr._review_date({"created_at": "not-a-date"}, NOW) == NOW
    assert sr._review_date({}, NOW) == NOW
    assert sr._review_date({"created_at": None}, NOW) == NOW
